[versions]
agp = "8.6.1"
appcompatVersion = "1.7.1"
circleimageview = "3.1.0"
constraintlayoutVersion = "2.2.1"
converterGson = "2.9.0"
dotsindicator = "5.0"
glide = "4.15.1"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
kotlinBom = "1.8.22"
material = "1.13.0"
activity = "1.12.2"
constraintlayout = "2.2.1"
materialVersion = "1.13.0"
junitJunit = "4.12"
recyclerview = "1.4.0"

[libraries]
#noinspection SimilarGradleDependency
appcompat-v161 = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageview" }
#noinspection SimilarGradleDependency
constraintlayout-v214 = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayoutVersion" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
dotsindicator = { module = "com.tbuonomo:dotsindicator", version.ref = "dotsindicator" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
#noinspection SimilarGradleDependency
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
#noinspection SimilarGradleDependency
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlinBom" }
#noinspection SimilarGradleDependency
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
#noinspection SimilarGradleDependency
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
#noinspection SimilarGradleDependency
material-v190 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "converterGson" }
junit-junit = { group = "junit", name = "junit", version.ref = "junitJunit" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }